/*in this example, stored locally in folder "ESS" on the C: drive*/
LIBNAME ESS "C:\ESS";
/*To create formats (value labels): edit and run ESSformats program*/
%include "C:\ESS\ESS9e03_1_formats.sas";
run;
data x;
set ESS.ESS9e03_1;
* MS file;
FORMAT
        cntry $CNTRY.
       nwspol NWSPOL.
     netusoft NETUSOFT.
      netustm NETUSTM.
      ppltrst PPLTRST.
      pplfair PPLFAIR.
       pplhlp PPLHLP.
      polintr POLINTR.
     psppsgva PSPPSGVA.
     actrolga ACTROLGA.
     psppipla PSPPIPLA.
     cptppola CPTPPOLA.
      trstprl TRSTPRL.
      trstlgl TRSTLGL.
      trstplc TRSTPLC.
      trstplt TRSTPLT.
      trstprt TRSTPRT.
       trstep TRSTEP.
       trstun TRSTUN.
         vote VOTE.
     prtvtcat PRTVTCAT.
     prtvtdbe PRTVTDBE.
     prtvtdbg PRTVTDBG.
     prtvtgch PRTVTGCH.
     prtvtbcy PRTVTBCY.
     prtvtecz PRTVTECZ.
     prtvede1 PRTVEDE1F.
     prtvede2 PRTVEDE2F.
     prtvtddk PRTVTDDK.
     prtvtgee PRTVTGEE.
     prtvtees PRTVTEES.
     prtvtdfi PRTVTDFI.
     prtvtdfr PRTVTDFR.
     prtvtcgb PRTVTCGB.
     prtvtahr PRTVTAHR.
     prtvtfhu PRTVTFHU.
     prtvtcie PRTVTCIE.
     prtvtcis PRTVTCIS.
     prtvtcit PRTVTCIT.
     prtvblt1 PRTVBLT1F.
     prtvblt2 PRTVBLT2F.
     prtvblt3 PRTVBLT3F.
     prtvtalv PRTVTALV.
      prtvtme PRTVTME.
     prtvtgnl PRTVTGNL.
     prtvtbno PRTVTBNO.
     prtvtdpl PRTVTDPL.
     prtvtcpt PRTVTCPT.
      prtvtrs PRTVTRS.
     prtvtcse PRTVTCSE.
     prtvtfsi PRTVTFSI.
     prtvtdsk PRTVTDSK.
      contplt CONTPLT.
      wrkprty WRKPRTY.
       wrkorg WRKORG.
        badge BADGE.
      sgnptit SGNPTIT.
       pbldmn PBLDMN.
       bctprd BCTPRD.
     pstplonl PSTPLONL.
      clsprty CLSPRTY.
     prtcldat PRTCLDAT.
     prtcldbe PRTCLDBE.
     prtcldbg PRTCLDBG.
     prtclgch PRTCLGCH.
     prtclbcy PRTCLBCY.
     prtclecz PRTCLECZ.
     prtclede PRTCLEDE.
     prtclddk PRTCLDDK.
     prtclgee PRTCLGEE.
     prtclfes PRTCLFES.
     prtclefi PRTCLEFI.
     prtclffr PRTCLFFR.
     prtclcgb PRTCLCGB.
     prtclahr PRTCLAHR.
     prtclghu PRTCLGHU.
     prtcleie PRTCLEIE.
     prtclcis PRTCLCIS.
     prtcldit PRTCLDIT.
     prtclblt PRTCLBLT.
     prtclalv PRTCLALV.
      prtclme PRTCLME.
     prtclfnl PRTCLFNL.
     prtclbno PRTCLBNO.
     prtclhpl PRTCLHPL.
     prtclept PRTCLEPT.
      prtclrs PRTCLRS.
     prtclcse PRTCLCSE.
     prtclfsi PRTCLFSI.
     prtcldsk PRTCLDSK.
      prtdgcl PRTDGCL.
      lrscale LRSCALE.
      stflife STFLIFE.
       stfeco STFECO.
       stfgov STFGOV.
       stfdem STFDEM.
       stfedu STFEDU.
      stfhlth STFHLTH.
      gincdif GINCDIF.
      freehms FREEHMS.
     hmsfmlsh HMSFMLSH.
      hmsacld HMSACLD.
        euftf EUFTF.
      imsmetn IMSMETN.
      imdfetn IMDFETN.
      impcntr IMPCNTR.
      imbgeco IMBGECO.
      imueclt IMUECLT.
      imwbcnt IMWBCNT.
        happy HAPPY.
      sclmeet SCLMEET.
      inprdsc INPRDSC.
       sclact SCLACT.
       crmvct CRMVCT.
      aesfdrk AESFDRK.
       health HEALTH.
      hlthhmp HLTHHMP.
      atchctr ATCHCTR.
      atcherp ATCHERP.
       rlgblg RLGBLG.
       rlgdnm RLGDNM.
     rlgdnbat RLGDNBAT.
      rlgdnbe RLGDNBE.
     rlgdnach RLGDNACH.
      rlgdncy RLGDNCY.
     rlgdnade RLGDNADE.
     rlgdnafi RLGDNAFI.
      rlgdngb RLGDNGB.
      rlgdnhu RLGDNHU.
      rlgdnie RLGDNIE.
     rlgdnais RLGDNAIS.
      rlgdnlt RLGDNLT.
      rlgdnlv RLGDNLV.
       rlgdme RLGDME.
      rlgdnnl RLGDNNL.
      rlgdnno RLGDNNO.
     rlgdnapl RLGDNAPL.
      rlgdnrs RLGDNRS.
     rlgdnase RLGDNASE.
     rlgdnask RLGDNASK.
      rlgblge RLGBLGE.
      rlgdnme RLGDNME.
     rlgdebat RLGDEBAT.
      rlgdebe RLGDEBE.
     rlgdeach RLGDEACH.
      rlgdecy RLGDECY.
     rlgdeade RLGDEADE.
     rlgdeafi RLGDEAFI.
      rlgdegb RLGDEGB.
      rlgdehu RLGDEHU.
      rlgdeie RLGDEIE.
     rlgdeais RLGDEAIS.
      rlgdelt RLGDELT.
      rlgdelv RLGDELV.
      rlgdeme RLGDEME.
      rlgdenl RLGDENL.
      rlgdeno RLGDENO.
     rlgdeapl RLGDEAPL.
      rlgders RLGDERS.
     rlgdease RLGDEASE.
     rlgdeask RLGDEASK.
       rlgdgr RLGDGR.
      rlgatnd RLGATND.
         pray PRAY.
      dscrgrp DSCRGRP.
      dscrrce DSCRRCE.
      dscrntn DSCRNTN.
      dscrrlg DSCRRLG.
      dscrlng DSCRLNG.
      dscretn DSCRETN.
      dscrage DSCRAGE.
      dscrgnd DSCRGND.
      dscrsex DSCRSEX.
      dscrdsb DSCRDSB.
      dscroth DSCROTH.
       dscrdk DSCRDK.
      dscrref DSCRREF.
      dscrnap DSCRNAP.
       dscrna DSCRNA.
      ctzcntr CTZCNTR.
     ctzshipd $CTZSHIPD.
      brncntr BRNCNTR.
     cntbrthd $CNTBRTHD.
     livecnta LIVECNTA.
      lnghom1 $LNGHOM1F.
      lnghom2 $LNGHOM2F.
      blgetmg BLGETMG.
       facntr FACNTR.
     fbrncntc $FBRNCNTC.
       mocntr MOCNTR.
     mbrncntc $MBRNCNTC.
        admdw ADMDW.
     vteurmmb VTEURMMB.
     vteumbgb VTEUMBGB.
     vteubcmb VTEUBCMB.
      evpdemp EVPDEMP.
      pdempyr PDEMPYR.
      lvpntyr LVPNTYR.
      evlvptn EVLVPTN.
      lvptnyr LVPTNYR.
        evmar EVMAR.
        maryr MARYR.
       bthcld BTHCLD.
      nbthcld NBTHCLD.
      fcldbrn FCLDBRN.
      ycldbyr YCLDBYR.
       ngchld NGCHLD.
      ygcdbyr YGCDBYR.
       ggchld GGCHLD.
        admge ADMGE.
      ageadlt AGEADLT.
      agemage AGEMAGE.
      ageoage AGEOAGE.
      iaglptn IAGLPTN.
        iagmr IAGMR.
       iagpnt IAGPNT.
       iagrtr IAGRTR.
      tygledu TYGLEDU.
       tyglvp TYGLVP.
        tygmr TYGMR.
       tygpnt TYGPNT.
       tygrtr TYGRTR.
      tolvpnt TOLVPNT.
       tochld TOCHLD.
       towkht TOWKHT.
       anvcld ANVCLD.
      alvgptn ALVGPTN.
      acldnmr ACLDNMR.
      aftjbyc AFTJBYC.
       advcyc ADVCYC.
       plnftr PLNFTR.
        hhmmb HHMMB.
         gndr GNDR.
        gndr2 GNDR2F.
        gndr3 GNDR3F.
        gndr4 GNDR4F.
        gndr5 GNDR5F.
        gndr6 GNDR6F.
        gndr7 GNDR7F.
        gndr8 GNDR8F.
        gndr9 GNDR9F.
       gndr10 GNDR10F.
       gndr11 GNDR11F.
       gndr12 GNDR12F.
       gndr13 GNDR13F.
       gndr14 GNDR14F.
       gndr15 GNDR15F.
         agea AGEA.
        yrbrn YRBRN.
       yrbrn2 YRBRN2F.
       yrbrn3 YRBRN3F.
       yrbrn4 YRBRN4F.
       yrbrn5 YRBRN5F.
       yrbrn6 YRBRN6F.
       yrbrn7 YRBRN7F.
       yrbrn8 YRBRN8F.
       yrbrn9 YRBRN9F.
      yrbrn10 YRBRN10F.
      yrbrn11 YRBRN11F.
      yrbrn12 YRBRN12F.
      yrbrn13 YRBRN13F.
      yrbrn14 YRBRN14F.
      yrbrn15 YRBRN15F.
      rshipa2 RSHIPA2F.
      rshipa3 RSHIPA3F.
      rshipa4 RSHIPA4F.
      rshipa5 RSHIPA5F.
      rshipa6 RSHIPA6F.
      rshipa7 RSHIPA7F.
      rshipa8 RSHIPA8F.
      rshipa9 RSHIPA9F.
     rshipa10 RSHIPA10F.
     rshipa11 RSHIPA11F.
     rshipa12 RSHIPA12F.
     rshipa13 RSHIPA13F.
     rshipa14 RSHIPA14F.
     rshipa15 RSHIPA15F.
      rshpsts RSHPSTS.
      rshpsgb RSHPSGB.
     lvgptnea LVGPTNEA.
     dvrcdeva DVRCDEVA.
       marsts MARSTS.
      marstgb MARSTGB.
     maritalb MARITALB.
      chldhhe CHLDHHE.
      domicil DOMICIL.
      edulvlb EDULVLB.
       eisced EISCED.
      edlveat EDLVEAT.
      edlvebe EDLVEBE.
      edlvebg EDLVEBG.
      edlvdch EDLVDCH.
      edlvgcy EDLVGCY.
      edlvdcz EDLVDCZ.
      edubde1 EDUBDE1F.
      eduade2 EDUADE2F.
      eduade3 EDUADE3F.
      edlvddk EDLVDDK.
      edlvdee EDLVDEE.
      edlvges EDLVGES.
      edlvdfi EDLVDFI.
      edlvdfr EDLVDFR.
      educgb1 EDUCGB1F.
      edubgb2 EDUBGB2F.
      edagegb EDAGEGB.
      edlvehr EDLVEHR.
      edlvdhu EDLVDHU.
      edlvdie EDLVDIE.
      edlvdis EDLVDIS.
      edlveit EDLVEIT.
      edlvdlt EDLVDLT.
      edlvdlv EDLVDLV.
      edlvdme EDLVDME.
      edlvenl EDLVENL.
      edlvdno EDLVDNO.
      edlvgpl EDLVGPL.
      edlvdpt EDLVDPT.
      edlvdrs EDLVDRS.
      edlvdse EDLVDSE.
      edlvesi EDLVESI.
      edlvdsk EDLVDSK.
       eduyrs EDUYRS.
        pdwrk PDWRK.
        edctn EDCTN.
       uempla UEMPLA.
       uempli UEMPLI.
        dsbld DSBLD.
         rtrd RTRD.
        cmsrv CMSRV.
        hswrk HSWRK.
       dngoth DNGOTH.
       dngref DNGREF.
        dngdk DNGDK.
        dngna DNGNA.
      mainact MAINACT.
      mnactic MNACTIC.
       crpdwk CRPDWK.
      pdjobev PDJOBEV.
      pdjobyr PDJOBYR.
      emplrel EMPLREL.
       emplno EMPLNO.
      wrkctra WRKCTRA.
        estsz ESTSZ.
        jbspv JBSPV.
       njbspv NJBSPV.
     wkdcorga WKDCORGA.
      iorgact IORGACT.
        wkhct WKHCT.
       icwhct ICWHCT.
       wkhtot WKHTOT.
       nacer2 NACER2F.
      tporgwk TPORGWK.
       isco08 ISCO08F.
      wrkac6m WRKAC6M.
       uemp3m UEMP3M.
      uemp12m UEMP12M.
      uemp5yr UEMP5YR.
        mbtru MBTRU.
     hincsrca HINCSRCA.
     hinctnta HINCTNTA.
      hincfel HINCFEL.
      iincsrc IINCSRC.
     edulvlpb EDULVLPB.
      eiscedp EISCEDP.
     edlvpeat EDLVPEAT.
     edlvpebe EDLVPEBE.
     edlvpebg EDLVPEBG.
     edlvpdch EDLVPDCH.
     edlvpgcy EDLVPGCY.
     edlvpdcz EDLVPDCZ.
     edupbde1 EDUPBDE1F.
     edupade2 EDUPADE2F.
     edupade3 EDUPADE3F.
     edlvpddk EDLVPDDK.
     edlvpdee EDLVPDEE.
     edlvpfes EDLVPFES.
     edlvpdfi EDLVPDFI.
     edlvpdfr EDLVPDFR.
     edupcgb1 EDUPCGB1F.
     edupbgb2 EDUPBGB2F.
     edagepgb EDAGEPGB.
     edlvpehr EDLVPEHR.
     edlvpdhu EDLVPDHU.
     edlvpdie EDLVPDIE.
     edlvpdis EDLVPDIS.
     edlvpeit EDLVPEIT.
     edlvpdlt EDLVPDLT.
     edlvpdlv EDLVPDLV.
     edlvpdme EDLVPDME.
     edlvpenl EDLVPENL.
     edlvpdno EDLVPDNO.
     edlvpfpl EDLVPFPL.
     edlvpdpt EDLVPDPT.
     edlvpdrs EDLVPDRS.
     edlvpdse EDLVPDSE.
     edlvpesi EDLVPESI.
     edlvpdsk EDLVPDSK.
       pdwrkp PDWRKP.
       edctnp EDCTNP.
      uemplap UEMPLAP.
      uemplip UEMPLIP.
       dsbldp DSBLDP.
        rtrdp RTRDP.
       cmsrvp CMSRVP.
       hswrkp HSWRKP.
      dngothp DNGOTHP.
       dngdkp DNGDKP.
      dngnapp DNGNAPP.
      dngrefp DNGREFP.
       dngnap DNGNAP.
       mnactp MNACTP.
      crpdwkp CRPDWKP.
      isco08p ISCO08P.
      emprelp EMPRELP.
      wkhtotp WKHTOTP.
     edulvlfb EDULVLFB.
      eiscedf EISCEDF.
     edlvfeat EDLVFEAT.
     edlvfebe EDLVFEBE.
     edlvfebg EDLVFEBG.
     edlvfdch EDLVFDCH.
     edlvfgcy EDLVFGCY.
     edlvfdcz EDLVFDCZ.
     edufbde1 EDUFBDE1F.
     edufade2 EDUFADE2F.
     edufade3 EDUFADE3F.
     edlvfddk EDLVFDDK.
     edlvfdee EDLVFDEE.
     edlvffes EDLVFFES.
     edlvfdfi EDLVFDFI.
     edlvfdfr EDLVFDFR.
     edufcgb1 EDUFCGB1F.
     edufbgb2 EDUFBGB2F.
     edagefgb EDAGEFGB.
     edlvfehr EDLVFEHR.
     edlvfdhu EDLVFDHU.
     edlvfdie EDLVFDIE.
     edlvfdis EDLVFDIS.
     edlvfeit EDLVFEIT.
     edlvfdlt EDLVFDLT.
     edlvfdlv EDLVFDLV.
     edlvfdme EDLVFDME.
     edlvfenl EDLVFENL.
     edlvfdno EDLVFDNO.
     edlvffpl EDLVFFPL.
     edlvfdpt EDLVFDPT.
     edlvfdrs EDLVFDRS.
     edlvfdse EDLVFDSE.
     edlvfesi EDLVFESI.
     edlvfdsk EDLVFDSK.
      emprf14 EMPRF14F.
      occf14b OCCF14B.
     edulvlmb EDULVLMB.
      eiscedm EISCEDM.
     edlvmeat EDLVMEAT.
     edlvmebe EDLVMEBE.
     edlvmebg EDLVMEBG.
     edlvmdch EDLVMDCH.
     edlvmgcy EDLVMGCY.
     edlvmdcz EDLVMDCZ.
     edumbde1 EDUMBDE1F.
     edumade2 EDUMADE2F.
     edumade3 EDUMADE3F.
     edlvmddk EDLVMDDK.
     edlvmdee EDLVMDEE.
     edlvmfes EDLVMFES.
     edlvmdfi EDLVMDFI.
     edlvmdfr EDLVMDFR.
     edumcgb1 EDUMCGB1F.
     edumbgb2 EDUMBGB2F.
     edagemgb EDAGEMGB.
     edlvmehr EDLVMEHR.
     edlvmdhu EDLVMDHU.
     edlvmdie EDLVMDIE.
     edlvmdis EDLVMDIS.
     edlvmeit EDLVMEIT.
     edlvmdlt EDLVMDLT.
     edlvmdlv EDLVMDLV.
     edlvmdme EDLVMDME.
     edlvmenl EDLVMENL.
     edlvmdno EDLVMDNO.
     edlvmfpl EDLVMFPL.
     edlvmdpt EDLVMDPT.
     edlvmdrs EDLVMDRS.
     edlvmdse EDLVMDSE.
     edlvmesi EDLVMESI.
     edlvmdsk EDLVMDSK.
      emprm14 EMPRM14F.
      occm14b OCCM14B.
      atncrse ATNCRSE.
      anctry1 ANCTRY1F.
      anctry2 ANCTRY2F.
      frprtpl FRPRTPL.
      gvintcz GVINTCZ.
      poltran POLTRAN.
       ifredu IFREDU.
       ifrjob IFRJOB.
      evfredu EVFREDU.
      evfrjob EVFRJOB.
       fvgabc FVGABC.
      infqbst INFQBST.
      grspnum GRSPNUM.
      grsplet GRSPLET.
      netinum NETINUM.
      netilet NETILET.
       grspfr GRSPFR.
       netifr NETIFR.
      frlgrsp FRLGRSP.
      frlneti FRLNETI.
      occinfr OCCINFR.
      topinfr TOPINFR.
      btminfr BTMINFR.
      wltdffr WLTDFFR.
      recskil RECSKIL.
       recexp RECEXP.
      recknow RECKNOW.
       recimg RECIMG.
      recgndr RECGNDR.
      sofrdst SOFRDST.
      sofrwrk SOFRWRK.
       sofrpr SOFRPR.
      sofrprv SOFRPRV.
      ppldsrv PPLDSRV.
      jstprev JSTPREV.
      pcmpinj PCMPINJ.
      ipcrtiv IPCRTIV.
      imprich IMPRICH.
      ipeqopt IPEQOPT.
      ipshabt IPSHABT.
      impsafe IMPSAFE.
      impdiff IMPDIFF.
      ipfrule IPFRULE.
      ipudrst IPUDRST.
      ipmodst IPMODST.
      ipgdtim IPGDTIM.
      impfree IMPFREE.
      iphlppl IPHLPPL.
      ipsuces IPSUCES.
      ipstrgv IPSTRGV.
      ipadvnt IPADVNT.
      ipbhprp IPBHPRP.
      iprspot IPRSPOT.
      iplylfr IPLYLFR.
       impenv IMPENV.
      imptrad IMPTRAD.
       impfun IMPFUN.
       region $REGION.
      regunit REGUNIT.
       inwdds INWDDS.
       inwmms INWMMS.
       inwyys INWYYS.
       inwshh INWSHH.
       inwsmm INWSMM.
       inwdde INWDDE.
       inwmme INWMME.
       inwyye INWYYE.
       inwehh INWEHH.
       inwemm INWEMM.

;
/*To create user-defined missing values .a, .b, .c and .d*/
*%include "C:\ESS\ESS_miss.sas";
run;
